trigger:
- main

pool:
  name: 'ubuntu-latest'
  
steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    azureSubscription: 'Vignesh-ServiceConnection'
    azureContainerRegistry: '{"loginServer":"vigneshwardevops.azurecr.io", "id" : "/subscriptions/23d9e783-b881-49e7-b2f1-a1a6f1bc2d90/resourceGroups/Vigneshwar-RG/providers/Microsoft.ContainerRegistry/registries/VigneshwarDevops"}'
    dockerFile: app/Dockerfile

- task: Docker@0
  displayName: 'Push an image'
  inputs:
    azureSubscription: 'Vignesh-ServiceConnection'
    azureContainerRegistry: '{"loginServer":"vigneshwardevops.azurecr.io", "id" : "/subscriptions/23d9e783-b881-49e7-b2f1-a1a6f1bc2d90/resourceGroups/Vigneshwar-RG/providers/Microsoft.ContainerRegistry/registries/VigneshwarDevops"}'
    action: 'Push an image'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'


